
import static java.awt.SystemColor.info;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 100 Mbps (Rigil Makmun)
 */
public class MainFormPD extends javax.swing.JFrame {

    /**
     * Creates new form MainFormPD
     */
    public MainFormPD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnShowMessage = new javax.swing.JButton();
        btnYesNoConfirm = new javax.swing.JButton();
        btnYesNoCancelConfirm = new javax.swing.JButton();
        btnInputDialogTextField = new javax.swing.JButton();
        btnInputDialogComboBox = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rbErrorMessage = new javax.swing.JRadioButton();
        rbInformation = new javax.swing.JRadioButton();
        rbWarning = new javax.swing.JRadioButton();
        rbPlan = new javax.swing.JRadioButton();
        txtDialog = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnShowMessage.setText("ShowMessage");
        btnShowMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowMessageActionPerformed(evt);
            }
        });

        btnYesNoConfirm.setText("Yes/No Confirm");
        btnYesNoConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesNoConfirmActionPerformed(evt);
            }
        });

        btnYesNoCancelConfirm.setText("Yes/No/Cancel Confirm");
        btnYesNoCancelConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesNoCancelConfirmActionPerformed(evt);
            }
        });

        btnInputDialogTextField.setText("Input Dialog (Text Field)");
        btnInputDialogTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputDialogTextFieldActionPerformed(evt);
            }
        });

        btnInputDialogComboBox.setText("Input Dialog (Combo Box)");
        btnInputDialogComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputDialogComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Message Type");

        buttonGroup1.add(rbErrorMessage);
        rbErrorMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbErrorMessage.setText("Error Message");

        buttonGroup1.add(rbInformation);
        rbInformation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbInformation.setText("Information");
        rbInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInformationActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbWarning);
        rbWarning.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbWarning.setText("Warning");

        buttonGroup1.add(rbPlan);
        rbPlan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbPlan.setText("Plan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnYesNoCancelConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnYesNoConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInputDialogTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInputDialogComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(rbErrorMessage)
                            .addComponent(rbInformation)
                            .addComponent(rbWarning)
                            .addComponent(rbPlan)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnShowMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnYesNoConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnYesNoCancelConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInputDialogTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInputDialogComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(rbErrorMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbInformation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbWarning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPlan)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowMessageActionPerformed
        // TODO add your handling code here:
        int optionType = 0;
        if(rbErrorMessage.isSelected()) optionType = JOptionPane.ERROR_MESSAGE;
        if(rbInformation.isSelected()) optionType = JOptionPane.INFORMATION_MESSAGE;
        if(rbWarning.isSelected()) optionType = JOptionPane.WARNING_MESSAGE;
        if(rbPlan.isSelected()) optionType = JOptionPane.PLAIN_MESSAGE;
        
        JOptionPane.showMessageDialog(null, "Contoh Show Message", "Title Message", optionType);
    }//GEN-LAST:event_btnShowMessageActionPerformed

    private void rbInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbInformationActionPerformed

    private void btnYesNoConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesNoConfirmActionPerformed
        // TODO add your handling code here:
        int optionType = 0;
        if(rbErrorMessage.isSelected()) optionType = JOptionPane.ERROR_MESSAGE;
        if(rbInformation.isSelected()) optionType = JOptionPane.INFORMATION_MESSAGE;
        if(rbWarning.isSelected()) optionType = JOptionPane.WARNING_MESSAGE;
        if(rbPlan.isSelected()) optionType = JOptionPane.PLAIN_MESSAGE;
        
        JOptionPane.showConfirmDialog(null, "Silahkan Pilih Yes atau No", "Confirm Title", JOptionPane.YES_NO_OPTION, optionType);
    }//GEN-LAST:event_btnYesNoConfirmActionPerformed

    private void btnYesNoCancelConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesNoCancelConfirmActionPerformed
        // TODO add your handling code here:
        int optionType = 0;
        if(rbErrorMessage.isSelected()) optionType = JOptionPane.ERROR_MESSAGE;
        if(rbInformation.isSelected()) optionType = JOptionPane.INFORMATION_MESSAGE;
        if(rbWarning.isSelected()) optionType = JOptionPane.WARNING_MESSAGE;
        if(rbPlan.isSelected()) optionType = JOptionPane.PLAIN_MESSAGE;
        
        JOptionPane.showConfirmDialog(null, "Silahkan Pilih Yes, No atau Cancel", "Confirm Title", JOptionPane.YES_NO_CANCEL_OPTION, optionType);
    }//GEN-LAST:event_btnYesNoCancelConfirmActionPerformed

    private void btnInputDialogTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputDialogTextFieldActionPerformed
        // TODO add your handling code here:
        int optionType = 0;
        if(rbErrorMessage.isSelected()) optionType = JOptionPane.ERROR_MESSAGE;
        if(rbInformation.isSelected()) optionType = JOptionPane.INFORMATION_MESSAGE;
        if(rbWarning.isSelected()) optionType = JOptionPane.WARNING_MESSAGE;
        if(rbPlan.isSelected()) optionType = JOptionPane.PLAIN_MESSAGE;
        
        //Mengubah menjadi variabel hasil
        String hasil = JOptionPane.showInputDialog(null, "Masukkan nama Anda disini : ", "Input Dialog Title", optionType);
        
        //Menampilkan hasil di TextField
        txtDialog.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnInputDialogTextFieldActionPerformed

    private void btnInputDialogComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputDialogComboBoxActionPerformed
        // TODO add your handling code here:
        int optionType = 0;
        if(rbErrorMessage.isSelected()) optionType = JOptionPane.ERROR_MESSAGE;
        if(rbInformation.isSelected()) optionType = JOptionPane.INFORMATION_MESSAGE;
        if(rbWarning.isSelected()) optionType = JOptionPane.WARNING_MESSAGE;
        if(rbPlan.isSelected()) optionType = JOptionPane.PLAIN_MESSAGE;
        
        String[] Options = {"Apple", "Mangga", "Nanas", "Jeruk"};
        JOptionPane.showInputDialog(null, "Pilih buah kesukaan Anda?", "Title Pilih Buah", optionType, null, Options, "Apple");
    }//GEN-LAST:event_btnInputDialogComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormPD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormPD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormPD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormPD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormPD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInputDialogComboBox;
    private javax.swing.JButton btnInputDialogTextField;
    private javax.swing.JButton btnShowMessage;
    private javax.swing.JButton btnYesNoCancelConfirm;
    private javax.swing.JButton btnYesNoConfirm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbErrorMessage;
    private javax.swing.JRadioButton rbInformation;
    private javax.swing.JRadioButton rbPlan;
    private javax.swing.JRadioButton rbWarning;
    private javax.swing.JTextField txtDialog;
    // End of variables declaration//GEN-END:variables
}
